Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-16.04"
 config.ssh.insert_key = false

  prg_nodes = [
    { :hostname => 'prg1', :ip => '172.10.0.10' },
    { :hostname => 'prg2', :ip => '172.10.0.11' },
    { :hostname => 'prg3', :ip => '172.10.0.12' },
  ]

  glab_nodes = [
      { :hostname => 'glab1', :ip => '172.10.0.40' },
      { :hostname => 'glab2', :ip => '172.10.0.41' },
    ]


  # Spin up prg boxes
  prg_nodes.each_with_index do |node, index|
    config.vm.define node[:hostname] do |config|
      config.vm.hostname = node[:hostname]
      config.vm.network :private_network, ip: node[:ip]

       config.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
       end

      # Add hosts to hostfile
      prg_nodes.each do | i | 
        config.vm.provision "shell", inline: "echo #{i[:ip]} #{i[:hostname]} >> /etc/hosts"
      end

      # Run ansible playbook
      if index  == prg_nodes.size - 1
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "prg.yml"
          ansible.inventory_path = "hosts"
          # Disable default limits to connect to all the machines
          ansible.limit = "all"
          ansible.verbose = "-v"
        end # end provision
      end # end if

    end # end config
  end # end prg nodes

  glab_nodes.each_with_index do |node, index|
    config.vm.define node[:hostname] do |config|
      config.vm.hostname = node[:hostname]
      config.vm.network :private_network, ip: node[:ip]

       config.vm.provider "virtualbox" do |vb|
            vb.memory = "2548"
            vb.cpus = 2
       end

      # Add hosts to hostfile
      glab_nodes.each do | i | 
        config.vm.provision "shell", inline: "echo #{i[:ip]} #{i[:hostname]} >> /etc/hosts"
      end

      # Run ansible playbook
      if index  == glab_nodes.size - 1
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "gitlab.yml"
          ansible.inventory_path = "hosts"
          # Disable default limits to connect to all the machines
          ansible.limit = "all"
          ansible.verbose = "-v"
        end # end provision
      end # end if

    end # end config
  end # end glab nodes

end # end vagrant
